context:
  version: "0.7.2"

package:
  name: "pycountry-convert"
  version: ${{ version }}

source:
  path: ..

build:
  number: 0
  script:
    - pip install --no-deps --no-build-isolation --ignore-installed .
  noarch: python

requirements:
  host:
    - python
    - pip
    - setuptools-scm

  run:
    - python
    - pprintpp >= 0.2.3
    - pycountry >= 16.11.27.1
    - wheel >= 0.29.0

tests:
  - python:
      pip_check: true
      imports:
        - pycountry_convert

about:
  homepage: https://github.com/jefftune/pycountry-convert
  license: MIT
  license_file: LICENSE
  summary: "Countries conversion functions for Python"
  description: |
    A Python package that provides functions for converting between country names,
    ISO 3166-1 alpha-2, alpha-3 codes, and numeric codes. It is useful for data
    analysis and projects involving geographical data.
  repository: https://github.com/nmcdtu/pycountry-convert
